trigger:
- master

pool:
  vmImage: 'windows-2019'

steps:
- powershell: |
    .\genbgfx.ps1
  displayName: 'Generate BGFX solutions'
- powershell: |
    .\buildbgfx.ps1
  displayName: 'Build BGFX solutions'
- powershell: |
    .\build.ps1
  displayName: 'Build BGFX.Net'
- powershell: |
    .\packbinary.ps1
  displayName: 'Package binary'

