trigger:
- master

pool:
  vmImage: 'windows-2019'

steps:
- powershell: |
    git clone https://github.com/bkaradzic/bx 
    git clone https://github.com/bkaradzic/bimg 
    git clone https://github.com/bkaradzic/bgfx
    cd bgfx 
    ..\bx\tools\bin\windows\genie --with-tools --with-shared-lib vs2019
    Get-ChildItem -Recurse
  displayName: 'Fetch bgfx and Setup for build'
