trigger:
- master
variables:
  IS_PIPELINE: 'true'
pool:
  vmImage: 'windows-2019'

steps:
- checkout: self
  submodules: true
  lfs: true
- powershell: |
    &choco install nuget.commandline
    .\genbgfx.ps1
  displayName: 'Generate BGFX solutions'
- powershell: |
    .\buildbgfx.ps1
  displayName: 'Build BGFX solutions'
- powershell: |
    .\build.ps1
  displayName: 'Build BGFX.Net'
- powershell: |
    .\packbinary.ps1
  displayName: 'Package binary'

